name: Move CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Sui
        run: |
          curl -sfLO https://github.com/MystenLabs/sui/releases/download/testnet-v1.69.2/sui-testnet-v1.69.2-ubuntu-x86_64.tgz
          tar -xzf sui-testnet-v1.69.2-ubuntu-x86_64.tgz
          sudo mv sui /usr/local/bin/
          sui --version

      - name: Verify Sui Installation
        run: sui --version

      - name: Move Build
        run: sui move build

      - name: Move Test
        run: sui move test
